FROM --platform=linux/amd64 golang:1.21 as builder
WORKDIR /app
COPY . .
WORKDIR /app/perf
RUN echo $(ls -1 .)
RUN go mod tidy && make build.amd64

FROM --platform=linux/amd64 golang:1.21
WORKDIR /app/perf
COPY --from=0 /app/perf/bin/amd64/* /bin/
