---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.datamodelName }}-crds
  namespace: {{ default  .Release.Namespace .Values.namespace }}
type: Opaque
data:
{{ (.Files.Glob "crds/*").AsSecrets | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.datamodelName }}-dmi
  namespace: {{ default  .Release.Namespace .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
      - command:
          - /bin/bash
          - -c
          - opt/datamodel-installer-job-cm/create_datamodel_cm.sh
        env:
          - name: KUBECONFIG
            value: /etc/config/kubeconfig
          - name: NAME
            value: {{ .Values.datamodelName }}
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
        name: datamodel-installer-job
        volumeMounts:
          - mountPath: /opt/datamodel-installer-job-cm/
            name: dmi-script
            readOnly: true
          - mountPath: /etc/config
            name: dmi-kubeconfig
            readOnly: true
          - mountPath: /crds
            name: {{ .Values.datamodelName }}-crds
            readOnly: true
      restartPolicy: Never
      volumes:
      - configMap:
          name: dmi-script
          defaultMode: 0555
        name: dmi-script
      - configMap:
          name: dmi-kubeconfig
          defaultMode: 0555
        name: dmi-kubeconfig
      - secret:
          secretName: {{ .Values.datamodelName }}-crds
        name: {{ .Values.datamodelName }}-crds
