---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.datamodelName }}-dmi
  namespace: {{ default  .Release.Namespace .Values.global.namespace }}
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
      - image: {{ .Values.image }}
        env:
          - name: KUBECONFIG
            value: /etc/config/kubeconfig
          - name: NAME
            value: {{ .Values.global.datamodelName }}
        imagePullPolicy: Always
        name: datamodel-installer-job
        volumeMounts:
          - mountPath: /opt/datamodel-installer-job-cm/
            name: dmi-script
            readOnly: true
          - mountPath: /etc/config
            name: dmi-kubeconfig
            readOnly: true
      restartPolicy: Never
      volumes:
      - configMap:
          name: dmi-script
          defaultMode: 0555
        name: dmi-script
      - configMap:
          name: dmi-kubeconfig
          defaultMode: 0555
        name: dmi-kubeconfig
